name: "Lint PR"

# ref: https://github.com/amannn/action-semantic-pull-request#event-triggers
on:
  pull_request:
  # ref: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
    types:
      - opened
      - edited
      - synchronize
  pull_request_target:
  # ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
